# Change these first
owner: orangemn6 # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: OrangeBin
    url: https://bin.orangemn6.xyz
  - name: The Epic Proxy that too many people use
    url: https://68656e647279646564.cf/
  - name: OrangeChat
    url: https://chat.orangemn6.xyz
  - name: OS in Browser
    url: https://genow.cf

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Orangemn6's status page for his websites. Powered by github actions."
  introMessage: See which of my websites are up, which are down, and which are broken here!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
